workspace = special:control, floating:true

bind = $mainMod, Escape, exec, bash $HOME/.config/Rices/rices/Iceberg/hypr/conf/launcher.bash

windowrulev2 = stayfocused, class:^(Rofi)$

windowrulev2 = workspace, workspace_name:^special:control$, class:^(Btop)$
windowrulev2 = float, workspace_name:^special:control$, class:^(Btop)$
