workspace = special:control, floating:true

bind = $mainMod, Escape, exec, bash $HOME/.config/Rices/rices/Iceberg/scripts/launcher.bash

windowrulev2 = workspace special:control, class:^(Btop)$
windowrulev2 = float, class:^(Btop)$
windowrulev2 = size 45% 55%, class:^(Btop)$
windowrulev2 = move 5% 5%, class:^(Btop)$

windowrulev2 = workspace special:control, class:^(Rofi)$
windowrulev2 = float, class:^(Rofi)$
windowrulev2 = center, class:^(Rofi)$
#windowrulev2 = stayfocused, class:^(Rofi)$
